const lv = {
  AF: 'Afganistāna',
  AL: 'Albānija',
  DZ: 'Alžīrija',
  AS: 'ASV Samoa',
  AD: 'Andora',
  AO: 'Angola',
  AI: 'Angilja',
  AQ: 'Antarktika',
  AG: 'Antigva un Barbuda',
  AR: 'Argentīna',
  AM: 'Armēnija',
  AW: 'Aruba',
  AU: 'Austrālija',
  AT: 'Austrija',
  AZ: 'Azerbaidžāna',
  BS: 'Bahamas',
  BH: 'Bahreina',
  BD: 'Bangladeša',
  BB: 'Barbadosa',
  BY: 'Baltkrievija',
  BE: 'Beļģija',
  BZ: 'Beliza',
  BJ: 'Benina',
  BM: 'Bermuda',
  BT: 'Butāna',
  BO: 'Bolīvija',
  BQ: 'Bonēra, Sintēstatiusa un Saba',
  BA: 'Bosnija un Hercegovina',
  BW: 'Botsvāna',
  BV: 'Buvē sala',
  BR: 'Brazīlija',
  IO: 'Apvienotās Karalistes Indijas okeāna teritorija',
  BN: 'Bruneja',
  BG: 'Bulgārija',
  BF: 'Burkinafaso',
  BI: 'Burundi',
  CV: 'Kaboverde',
  KH: 'Kambodža',
  CM: 'Kamerūna',
  CA: 'Kanāda',
  KY: 'Kaimanu Salas',
  CF: 'Centrālāfrikas Republika',
  TD: 'Čada',
  CL: 'Čīle',
  CN: 'Ķīna',
  CX: 'Ziemassvētku Sala',
  CC: 'Kokosu (Kīlinga) salas',
  CO: 'Kolumbija',
  KM: 'Komoras',
  CD: 'Kongo Demokrātiskā Republika',
  CG: 'Kongo',
  CK: 'Kuka salas',
  CR: 'Kostarika',
  HR: 'Horvātija',
  CU: 'Kuba',
  CW: 'Kirasao',
  CY: 'Kipra',
  CZ: 'Čehija',
  CI: 'Kotdivuāra',
  DK: 'Dānija',
  DJ: 'Džibutija',
  DM: 'Dominika',
  DO: 'Dominikāna',
  EC: 'Ekvadora',
  EG: 'Ēģipte',
  SV: 'Salvadora',
  GQ: 'Ekvatoriālā Gvineja',
  ER: 'Eritreja',
  EE: 'Igaunija',
  SZ: 'Svazilenda',
  ET: 'Etiopija',
  FK: 'Folklenda Salas',
  FO: 'Farēru Salas',
  FJ: 'Fidži',
  FI: 'Somija',
  FR: 'Francija',
  GF: 'Gviāna',
  PF: 'Franču Polinēzija',
  TF: 'Francijas Dienvidjūru un Antarktikas Zemes',
  GA: 'Gabona',
  GM: 'Gambija',
  GE: 'Gruzijā',
  DE: 'Vācija',
  GH: 'Gana',
  GI: 'Gibraltārs',
  GR: 'Grieķija',
  GL: 'Grenlande',
  GD: 'Grenāda',
  GP: 'Gvadelupa',
  GU: 'Guama',
  GT: 'Gvatemala',
  GG: 'Gērnsija',
  GN: 'Gvineja',
  GW: 'Gvineja-Bisava',
  GY: 'Gujāna',
  HT: 'Haiti',
  HM: 'Hērda Sala un Makdonalda Salas',
  VA: 'Vatikāns',
  HN: 'Hondurasa',
  HK: 'Honkonga',
  HU: 'Ungārija',
  IS: 'Islande',
  IN: 'Indija',
  ID: 'Indonēzija',
  IR: 'Irāna',
  IQ: 'Irāka',
  IE: 'Īrija',
  IM: 'Mena',
  IL: 'Izraēla',
  IT: 'Itālija',
  JM: 'Jamaika',
  JP: 'Japāna',
  JE: 'Džērsija',
  JO: 'Jordānija',
  KZ: 'Kazahstāna',
  KE: 'Kenija',
  KI: 'Kiribati',
  KP: 'Ziemeļkoreja',
  KR: 'Dienvidkoreja',
  KW: 'Kuveita',
  KG: 'Kirgizstāna',
  LA: 'Laosa',
  LV: 'Latvija',
  LB: 'Libāna',
  LS: 'Lesoto',
  LR: 'Liberija',
  LY: 'Lībija',
  LI: 'Lihtenšteina',
  LT: 'Lietuva',
  LU: 'Luksemburga',
  MO: 'Makao',
  MG: 'Madagaskara',
  MW: 'Malāvija',
  MY: 'Malēja',
  MV: 'Maldīvja',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Māršala salas',
  MQ: 'Martinika',
  MR: 'Mauritānija',
  MU: 'Maurīcija',
  YT: 'Majota',
  MX: 'Meksika',
  FM: 'Mikronēzija',
  MD: 'Moldova',
  MC: 'Monako',
  MN: 'Mongolija',
  ME: 'Melnkalne',
  MS: 'Montserrata',
  MA: 'Maroka',
  MZ: 'Mozambika',
  MM: 'Mjanma',
  NA: 'Namībija',
  NR: 'Nauru',
  NP: 'Nepāla',
  NL: 'Nīderlande',
  NC: 'Jaunkaledonija',
  NZ: 'Jaunzēlande',
  NI: 'Nikaragva',
  NE: 'Nigēra',
  NG: 'Nigērija',
  NU: 'Niue',
  NF: 'Norfolka',
  MP: 'Ziemeļu Marianas salas',
  NO: 'Norvēģija',
  OM: 'Omāna',
  PK: 'Pakistāna',
  PW: 'Palau',
  PS: 'Palestīna',
  PA: 'Panama',
  PG: 'Papua-Jaungvineja',
  PY: 'Paragvaja',
  PE: 'Peru',
  PH: 'Filipīnas',
  PN: 'Pitkērna',
  PL: 'Polija',
  PT: 'Portugāle',
  PR: 'Puertoriko',
  QA: 'Katara',
  MK: 'Ziemeļmaķedonija',
  RO: 'Rumānija',
  RU: 'Krievija',
  RW: 'Ruanda',
  RE: 'Reinjona',
  BL: 'Senbartelmī',
  SH: 'Svētās Helēnas Sala',
  KN: 'Sentkitsa un Nevisa',
  LC: 'Sentlūsija',
  MF: 'Senmartēna',
  PM: 'Senpjēra un Mikelona',
  VC: 'Sentvinsenta un Grenadīnas',
  WS: 'Samoa',
  SM: 'Sanmarīno',
  ST: 'Santome un Prinsipi',
  SA: 'Saūda Arābija',
  SN: 'Senegāla',
  RS: 'Serbija',
  SC: 'Seišelas',
  SL: 'Sjerraleone',
  SG: 'Singapūra',
  SX: 'Sintmārtena',
  SK: 'Slovākija',
  SI: 'Slovēnija',
  SB: 'Zālamana Salas',
  SO: 'Somālija',
  ZA: 'Dienvidāfrika',
  GS: 'Dienviddžordžija un Dienvidsendviču Salas',
  SS: 'Dienvidsudāna',
  ES: 'Spānija',
  LK: 'Šrilanka',
  SD: 'Sudāna',
  SR: 'Surinama',
  SJ: 'Svalbāra, Jana Majena sala',
  SE: 'Zviedrija',
  CH: 'Šveice',
  SY: 'Sīrija',
  TW: 'Taivāna',
  TJ: 'Tadžikistāna',
  TZ: 'Tanzānija',
  TH: 'Taizeme',
  TL: 'Austrumtimora',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidāda un Tobāgo',
  TN: 'Tunisija',
  TR: 'Turcija',
  TM: 'Turkmēnija',
  TC: 'Tērksas un Kaikosas',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraina',
  AE: 'Apvienotie Arābu Emirāti',
  GB: 'Lielbritānija',
  UM: 'ASV Mazās Aizjūru Salas',
  US: 'Amerikas Savienotās Valstis',
  UY: 'Urugvaja',
  UZ: 'Uzbekistāna',
  VU: 'Vanuatu',
  VE: 'Venecuēla',
  VN: 'Vjetnama',
  VG: 'Virdžīnu salas (Lielbritānija)',
  VI: 'Virdžīnu salas (ASV)',
  WF: 'Volisa un Futuna',
  EH: 'Rietumsahāra',
  YE: 'Jemena',
  ZM: 'Zambija',
  ZW: 'Zimbabve',
  AX: 'Ālandu Salas',
};

const en = {
  AF: 'Afghanistan',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua and Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas (the)',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia (Plurinational State of)',
  BQ: 'Bonaire, Sint Eustatius and Saba',
  BA: 'Bosnia and Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory (the)',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  CV: 'Cabo Verde',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  KY: 'Cayman Islands (the)',
  CF: 'Central African Republic (the)',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands (the)',
  CO: 'Colombia',
  KM: 'Comoros (the)',
  CD: 'Congo (the Democratic Republic of the)',
  CG: 'Congo (the)',
  CK: 'Cook Islands (the)',
  CR: 'Costa Rica',
  HR: 'Croatia',
  CU: 'Cuba',
  CW: 'Curaçao',
  CY: 'Cyprus',
  CZ: 'Czechia',
  CI: "Côte d'Ivoire",
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic (the)',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  SZ: 'Eswatini',
  ET: 'Ethiopia',
  FK: 'Falkland Islands (the) [Malvinas]',
  FO: 'Faroe Islands (the)',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories (the)',
  GA: 'Gabon',
  GM: 'Gambia (the)',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard Island and McDonald Islands',
  VA: 'Holy See (the)',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran (Islamic Republic of)',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KP: "Korea (the Democratic People's Republic of)",
  KR: 'Korea (the Republic of)',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: "Lao People's Democratic Republic (the)",
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macao',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands (the)',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia (Federated States of)',
  MD: 'Moldova (the Republic of)',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands (the)',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger (the)',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MK: 'North Macedonia',
  MP: 'Northern Mariana Islands (the)',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestine, State of',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines (the)',
  PN: 'Pitcairn',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  RO: 'Romania',
  RU: 'Russian Federation (the)',
  RW: 'Rwanda',
  RE: 'Réunion',
  BL: 'Saint Barthélemy',
  SH: 'Saint Helena, Ascension and Tristan da Cunha',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin (French part)',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and the Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome and Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SX: 'Sint Maarten (Dutch part)',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia and the South Sandwich Islands',
  SS: 'South Sudan',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan (the)',
  SR: 'Suriname',
  SJ: 'Svalbard and Jan Mayen',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syrian Arab Republic',
  TW: 'Taiwan (Province of China)',
  TJ: 'Tajikistan',
  TZ: 'Tanzania, United Republic of',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks and Caicos Islands (the)',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates (the)',
  GB: 'United Kingdom of Great Britain and Northern Ireland (the)',
  UM: 'United States Minor Outlying Islands (the)',
  US: 'United States of America (the)',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela (Bolivarian Republic of)',
  VN: 'Viet Nam',
  VG: 'Virgin Islands (British)',
  VI: 'Virgin Islands (U.S.)',
  WF: 'Wallis and Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  AX: 'Åland Islands',
};

export function countryCodeToName(countryCode, lang = 'lv') {
  if (lang === 'lv' || lang === 'LV') return lv[countryCode];
  if (lang === 'en' || lang === 'EN') return en[countryCode];
  return null;
}
